<?php
/**
 * @file
 * Main bootstrap file of the tmgmt_google module.
 */


/**
 * Implements hook_tmgmt_translator_plugin_info().
 */
function tmgmt_google_tmgmt_translator_plugin_info() {
  return array(
    'google' => array(
      'label' => t('Google translator'),
      'description' => t('Google Translator service.'),
      'plugin controller class' => 'TMGMTGoogleTranslatorPluginController',
      'ui controller class' => 'TMGMTGoogleTranslatorUIController',
      'default settings' => array(
        'api_key' => '',
      ),
    ),
  );
}

/**
 * Local Exception class
 */
class TMGMTGoogleException extends Exception {

  /**
   * @param string $message
   * @param array $data
   *   Associative array of dynamic data that will be inserted into $message.
   * @param int $code
   */
  function __construct($message = "", $data = array(), $code = 0) {
    parent::__construct(strtr($message, $data), $code);
  }
}
